# our main "server" worker

name = 'spatial-compute'
main = 'src/server/index.tsx'
compatibility_date = '2024-08-30'
compatibility_flags = ["nodejs_compat_v2"]

legacy_assets = './public'

# [build]
# command = "tailwindcss -i ./src/client/styles.css -o ./public/dist/styles.css"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "pokemon"
database_id = "1bea6938-8777-4864-a72e-f5fa2179411f"

[[services]]
service = "pokemon-fetch"
binding = "POKEMON"

[[durable_objects.bindings]]
name = "Session"
class_name = "Session"

 [[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Session"]


# [[unsafe.bindings]]
# name = "LIMITER"
# type = "ratelimit"
# namespace_id = "3141"
# simple = { limit = 20, period = 10 }
